name: Test Astro Website
description: |
  This workflow tests your Astro site.
  It runs linting and other checks to ensure code quality.

runs:
  using: "composite"
  steps:
    - name: Checkout your repository using git
      uses: actions/checkout@v7
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      shell: bash
      run: |
        corepack enable
        corepack prepare --activate
        yarn install --immutable
    - name: Run Astro Lint
      shell: bash
      run: |
        yarn lint
